### ISSUE TITLE
paper update 

### ISSUE THREAD

**Issue by ZhongLIFR** [yuan-shuhan/trustworthy-anomaly-detection-papers#1]
Dear Shuhan,

Thank you for this awesome repo and also citing our paper "a survey on explainable anomaly detection." For your information, this ArXiv paper has been accepted by The ACM Transactions on Knowledge Discovery from Data (TKDD) journal for publication and here is the [link](https://dl.acm.org/doi/10.1145/3609333). I would appreciate it if you can update this information. 

Best,

Zhong

**Comment by yuan-shuhan** [comment]
Updated. Thanks for sharing.
